### ISSUE TITLE
Announcement issues

### ISSUE THREAD

**Issue by Midzzz** [ZergRael/LootArchive#3]
Hello,

When I use /la give (item), I don't get an announce in raid or raid warning even when I select it in the options tab. Same issue when I use /la give (charname) (item).

Tracking is fine, got the message for myself and the addon records it well but the announcement system seems broken.

Thanks for your work btw, this addon is fucking great !

**Comment by ZergRael** [comment]
Somehow I left a debug statement in there, terribly sorry.
Will update after some testing.

**Comment by Midzzz** [comment]
Nice !

Thanks for your work, it truly help us managing loots in raid.
